/* Generated By:JavaCC: Do not edit this line. SimpleLexerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleLexerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AT = 5;
  /** RegularExpression Id. */
  int OR = 6;
  /** RegularExpression Id. */
  int OP = 7;
  /** RegularExpression Id. */
  int CP = 8;
  /** RegularExpression Id. */
  int OB = 9;
  /** RegularExpression Id. */
  int CB = 10;
  /** RegularExpression Id. */
  int COMMA = 11;
  /** RegularExpression Id. */
  int PP = 12;
  /** RegularExpression Id. */
  int FORWARD = 13;
  /** RegularExpression Id. */
  int CLEARSCREEN = 14;
  /** RegularExpression Id. */
  int PENUP = 15;
  /** RegularExpression Id. */
  int PENDOWN = 16;
  /** RegularExpression Id. */
  int HIDETURTLE = 17;
  /** RegularExpression Id. */
  int SHOWTURTLE = 18;
  /** RegularExpression Id. */
  int HOME = 19;
  /** RegularExpression Id. */
  int SETX = 20;
  /** RegularExpression Id. */
  int SETY = 21;
  /** RegularExpression Id. */
  int SETXY = 22;
  /** RegularExpression Id. */
  int SETHEADING = 23;
  /** RegularExpression Id. */
  int ARC = 24;
  /** RegularExpression Id. */
  int CHANGESHAPE = 25;
  /** RegularExpression Id. */
  int POS = 26;
  /** RegularExpression Id. */
  int XCOR = 27;
  /** RegularExpression Id. */
  int YCOR = 28;
  /** RegularExpression Id. */
  int HEADING = 29;
  /** RegularExpression Id. */
  int TOWARDS = 30;
  /** RegularExpression Id. */
  int LABEL = 31;
  /** RegularExpression Id. */
  int SETLABELHEIGHT = 32;
  /** RegularExpression Id. */
  int REPEAT = 33;
  /** RegularExpression Id. */
  int BACK = 34;
  /** RegularExpression Id. */
  int SETWIDTH = 35;
  /** RegularExpression Id. */
  int SETCOLOR = 36;
  /** RegularExpression Id. */
  int PRINT = 37;
  /** RegularExpression Id. */
  int RANDOM = 38;
  /** RegularExpression Id. */
  int LEFT = 39;
  /** RegularExpression Id. */
  int RIGHT = 40;
  /** RegularExpression Id. */
  int MAKE = 41;
  /** RegularExpression Id. */
  int SUM = 42;
  /** RegularExpression Id. */
  int DIFFERENCE = 43;
  /** RegularExpression Id. */
  int PROCEDURE = 44;
  /** RegularExpression Id. */
  int END = 45;
  /** RegularExpression Id. */
  int VARIABLE = 46;
  /** RegularExpression Id. */
  int INT = 47;
  /** RegularExpression Id. */
  int DIGIT = 48;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"@\"",
    "\"|\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"::\"",
    "<FORWARD>",
    "<CLEARSCREEN>",
    "\"Penup\"",
    "\"Pendown\"",
    "\"Hideturtle\"",
    "\"Showturtle\"",
    "\"Home\"",
    "\"Setx\"",
    "\"Sety\"",
    "\"Setxy\"",
    "<SETHEADING>",
    "\"Arc\"",
    "<CHANGESHAPE>",
    "\"Pos\"",
    "\"Xcor\"",
    "\"Ycor\"",
    "\"Heading\"",
    "\"Towards\"",
    "\"Label\"",
    "\"Setlabelheight\"",
    "\"repeat\"",
    "<BACK>",
    "\"Setwidth\"",
    "\"Setcolor\"",
    "\"Print\"",
    "\"Random\"",
    "<LEFT>",
    "<RIGHT>",
    "\"Make\"",
    "\"Sum\"",
    "\"Difference\"",
    "\"To\"",
    "\"end\"",
    "<VARIABLE>",
    "<INT>",
    "<DIGIT>",
    "\":\"",
  };

}
